question_data = [{"category": "Animals", "type": "boolean", "difficulty": "easy",
         "question": "The Axolotl is an amphibian that can spend its whole life in a larval state.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Science & Nature", "type": "boolean", "difficulty": "medium",
         "question": "The Doppler effect applies to light.", "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Entertainment: Film", "type": "boolean", "difficulty": "easy",
         "question": "The movie ''The Nightmare before Christmas'' was all done with physical objects.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Geography", "type": "boolean", "difficulty": "medium",
         "question": "The flag of South Africa features 7 colours.", "correct_answer": "False",
         "incorrect_answers": ["True"]}, {"category": "Entertainment: Music", "type": "boolean", "difficulty": "easy",
                                          "question": "The music video to The Buggle's ''Video Killed the Radio Star'' was the first music video to broadcast on MTV.",
                                          "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Geography", "type": "boolean", "difficulty": "easy",
         "question": "Greenland is covered with grass and Iceland covered with ice.", "correct_answer": "False",
         "incorrect_answers": ["True"]}, {"category": "History", "type": "boolean", "difficulty": "medium",
                                          "question": "In World War II, Hawker Typhoons served in the Pacific theater.",
                                          "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "General Knowledge", "type": "boolean", "difficulty": "hard",
         "question": "This is the correct spelling of ''Supercalifragilisticexpialidocious''.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Geography", "type": "boolean", "difficulty": "easy",
         "question": "Alaska is the largest state in the United States.", "correct_answer": "True",
         "incorrect_answers": ["False"]}, {"category": "Art", "type": "boolean", "difficulty": "medium",
                                           "question": "Vincent van Gogh cut off one of his ears.",
                                           "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "hard",
         "question": "The first ''Metal Gear'' game was released for the PlayStation 1.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "Entertainment: Music", "type": "boolean", "difficulty": "medium",
         "question": "Ashley Frangipane performs under the stage name Halsey.", "correct_answer": "True",
         "incorrect_answers": ["False"]},
        {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
         "question": "Big the Cat is a playable character in ''Sonic Generations''.", "correct_answer": "False",
         "incorrect_answers": ["True"]}, {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
                                          "question": "Cucumbers are usually more than 90% water.",
                                          "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Geography", "type": "boolean", "difficulty": "medium",
         "question": "Vietnam is the only country in the world that starts with V. ", "correct_answer": "False",
         "incorrect_answers": ["True"]},
        {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "medium",
         "question": "In World of Warcraft lore, Thrall is the original wielder of ''Doomhammer''.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "Politics", "type": "boolean", "difficulty": "easy", "question": "Denmark has a monarch.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
         "question": "Sitting for more than three hours a day can cut two years off a person's life expectancy.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
         "question": "Minecraft can be played with a virtual reality headset.", "correct_answer": "True",
         "incorrect_answers": ["False"]}, {"category": "Geography", "type": "boolean", "difficulty": "medium",
                                           "question": "There exists an island named ''Java''.",
                                           "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Entertainment: Film", "type": "boolean", "difficulty": "easy",
         "question": "In Alfred Hitchcock's film 'Psycho' it is said he used chocolate syrup to simulate the blood in the famous shower scene from ",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "medium",
         "question": "TF2: The Heavy's voice actor, Gary Schwartz, voices the Demoman as well ",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Science: Gadgets", "type": "boolean", "difficulty": "medium",
         "question": "The Western Electric Model 500 telephone uses tone dialing to dial phone numbers.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
         "question": "Rebecca Chambers does not appear in any Resident Evil except for the original Resident Evil and the Gamecube remake.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "Science: Computers", "type": "boolean", "difficulty": "hard",
         "question": "DHCP stands for Dynamic Host Configuration Port.", "correct_answer": "False",
         "incorrect_answers": ["True"]}, {"category": "Geography", "type": "boolean", "difficulty": "medium",
                                          "question": "Antarctica is the largest desert in the world.",
                                          "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Entertainment: Board Games", "type": "boolean", "difficulty": "easy",
         "question": "There is a Donald Trump Board Game, which was made in 1989.", "correct_answer": "True",
         "incorrect_answers": ["False"]}, {"category": "Entertainment: Books", "type": "boolean", "difficulty": "easy",
                                           "question": "''Elementary, my dear Watson'' is a phrase that is never truly said within the Conan Doyle books of Sherlock Holmes.",
                                           "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Entertainment: Music", "type": "boolean", "difficulty": "medium",
         "question": "EDM label Monstercat signs tracks instead of artists.", "correct_answer": "True",
         "incorrect_answers": ["False"]}, {"category": "Geography", "type": "boolean", "difficulty": "medium",
                                           "question": "Liechtenstein does not have an airport.",
                                           "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
         "question": "The first dual-core CPU was the Intel Pentium D.", "correct_answer": "False",
         "incorrect_answers": ["True"]}, {"category": "History", "type": "boolean", "difficulty": "easy",
                                          "question": "Adolf Hitler was tried at the Nuremberg trials.",
                                          "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "Politics", "type": "boolean", "difficulty": "easy",
         "question": "Donald Trump won the popular vote in the 2016 United States presidential election.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "Entertainment: Television", "type": "boolean", "difficulty": "easy",
         "question": "Klingons express emotion in art through opera and poetry.", "correct_answer": "True",
         "incorrect_answers": ["False"]},
        {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "medium",
         "question": "Resident Evil 4 was originally meant to be a Nintendo GameCube exclusive.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Entertainment: Television", "type": "boolean", "difficulty": "easy",
         "question": "In ''Star Trek'', Klingons are aliens.", "correct_answer": "True",
         "incorrect_answers": ["False"]},
        {"category": "Science: Mathematics", "type": "boolean", "difficulty": "medium",
         "question": "The set of all algebraic numbers is countable.", "correct_answer": "True",
         "incorrect_answers": ["False"]}, {"category": "Politics", "type": "boolean", "difficulty": "hard",
                                           "question": "George Clinton, Vice President of the United States (1805-1812), is an ancestor of President Bill Clinton.",
                                           "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "Politics", "type": "boolean", "difficulty": "medium",
         "question": "Helen Clark was the 37th Prime Minister of Australia.", "correct_answer": "False",
         "incorrect_answers": ["True"]}, {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
                                          "question": "Linus Sebastian is the creator of the Linux kernel, which went on to be used in Linux, Android, and Chrome OS.",
                                          "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "Science: Mathematics", "type": "boolean", "difficulty": "easy",
         "question": "The sum of any two odd integers is odd.", "correct_answer": "False",
         "incorrect_answers": ["True"]}, {"category": "Science & Nature", "type": "boolean", "difficulty": "easy",
                                          "question": "Celiac Disease is a disease that effects the heart, causing those effected to be unable to eat meat.",
                                          "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "History", "type": "boolean", "difficulty": "easy",
         "question": "Thomas Crapper was a plumber who invented the flushing toilet.", "correct_answer": "False",
         "incorrect_answers": ["True"]}, {"category": "Animals", "type": "boolean", "difficulty": "medium",
                                          "question": "Tigers have one colour of skin despite the stripey fur.",
                                          "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "Entertainment: Japanese Anime & Manga", "type": "boolean", "difficulty": "hard",
         "question": "The character Plum from ''No Game No Life'' is a girl.", "correct_answer": "False",
         "incorrect_answers": ["True"]},
        {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "medium",
         "question": "In the game ''Until Dawn'' Emily is the only playable character who can be killed by another playable character directly.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Geography", "type": "boolean", "difficulty": "hard",
         "question": "Only one country in the world starts with the letter Q.", "correct_answer": "True",
         "incorrect_answers": ["False"]}, {"category": "Science: Computers", "type": "boolean", "difficulty": "hard",
                                           "question": "The T-Mobile Sidekick smartphone is a re-branded version of the Danger Hiptop.",
                                           "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Entertainment: Music", "type": "boolean", "difficulty": "medium",
         "question": "Green Day's album 'American Idiot' is considered a ''punk rock opera.''",
         "correct_answer": "True", "incorrect_answers": ["False"]}]

quiz_game_art = """
  _______   ________   ________  ________   _______  ________  ________  ________ 
 ╱       ╲╲╱    ╱   ╲ ╱        ╲╱        ╲╱╱       ╲╱        ╲╱        ╲╱        ╲
╱        ╱╱         ╱_╱       ╱╱-        ╱╱      __╱         ╱         ╱         ╱
╲__      ╱         ╱╱         ╱        _╱       ╱ ╱         ╱         ╱        _╱ 
  ╲_____╱╲________╱ ╲________╱╲________╱╲________╱╲___╱____╱╲__╱__╱__╱╲________╱  

"""